name: "CI Build"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [ 'main' ]

env:
  PROJECT_NAME: Demo.Selenium.Bank
    

jobs:
  installations:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

  SND:
    name: SND
    needs: installations
    runs-on: ubuntu-latest
    environment: snd
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x      

      - name: Install dependencies
        run: dotnet restore src/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore src/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj

      - name: Tests
        run: dotnet test -e ApiSettings__BaseUrl=${{ vars.APISETTINGSBASEURL }} -e ApiSettings__UserName="${{ secrets.USERNAME }}" -e ApiSettings__Password="${{ secrets.PASSWORD }}" --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" src/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj


  DEV:
    name: DEV
    needs: installations
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout      
        uses: actions/checkout@v3

      - name: Setup .NET     
        uses: actions/setup-dotnet@v3   
        with:
          dotnet-version: |
            6.0.x      

      - name: Install dependencies
        run: dotnet restore src/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj 
        
      - name: Build
        run: dotnet build --configuration Release --no-restore src/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj

      - name: Tests
        run: dotnet test -e ApiSettings__BaseUrl=${{ vars.APISETTINGSBASEURL }} -e ApiSettings__UserName="${{ secrets.USERNAME }}" -e ApiSettings__Password="${{ secrets.PASSWORD }}" --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" src/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj

  UAT:
      name: UAT
      needs: [SND, DEV]
      runs-on: ubuntu-latest
      environment: uat
      steps:
        - name: Checkout      
          uses: actions/checkout@v3

        - name: Setup .NET     
          uses: actions/setup-dotnet@v3   
          with:
            dotnet-version: |
              6.0.x      

        - name: Install dependencies
          run: dotnet restore src/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj 
          
        - name: Build
          run: dotnet build --configuration Release --no-restore src/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj

        - name: Tests
          run: dotnet test -e ApiSettings__BaseUrl=${{ vars.APISETTINGSBASEURL }} -e ApiSettings__UserName="${{ secrets.USERNAME }}" -e ApiSettings__Password="${{ secrets.PASSWORD }}" --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" src/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj

  SIT:
    name: SIT
    needs: [UAT]
    runs-on: ubuntu-latest
    environment: sit
    steps:
      - name: Checkout      
        uses: actions/checkout@v3

      - name: Setup .NET     
        uses: actions/setup-dotnet@v3   
        with:
          dotnet-version: |
            6.0.x      

      - name: Install dependencies
        run: dotnet restore src/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj 
        
      - name: Build
        run: dotnet build --configuration Release --no-restore src/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj

      - name: Tests
        run: dotnet test -e ApiSettings__BaseUrl=${{ vars.APISETTINGSBASEURL }} -e ApiSettings__UserName="${{ secrets.USERNAME }}" -e ApiSettings__Password="${{ secrets.PASSWORD }}" --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" src/${{ env.PROJECT_NAME }}/${{ env.PROJECT_NAME }}.csproj
      
        