name: "CI Build"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches: [ 'main' ]

jobs:
  installations:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

  SND:
    name: SND
    needs: installations
    uses: ./.github/workflows/run-tests.yml
    with:
      projectName: Demo.Selenium.Bank
      environment: snd
    secrets:
      userName: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
  
  DEV:
    name: DEV
    needs: installations
    uses: ./.github/workflows/run-tests.yml
    with:
      projectName: Demo.Selenium.Bank
      environment: dev
    secrets:
      userName: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}
  
  SIT:
    name: SIT
    needs: [ SND, DEV ]
    uses: ./.github/workflows/run-tests.yml
    with:
      projectName: Demo.Selenium.Bank
      environment: sit
    secrets:
      userName: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}

  UAT:
    name: UAT
    needs: [ SIT ]
    uses: ./.github/workflows/run-tests.yml
    with:
      projectName: Demo.Selenium.Bank
      environment: uat
    secrets:
      userName: ${{ secrets.USERNAME }}
      password: ${{ secrets.PASSWORD }}