name: runtests

on:
  workflow_call:
    inputs:
      projectName:
        required: true
        type: string
      baseUrl:
        required: true
        type: string
    secrets:
      userName:
        required: true
      password:
        required: true

jobs:
  rundotnettests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            6.0.x      
      
      - name: Install dependencies
        run: dotnet restore src/${{ inputs.projectName }}/${{ inputs.projectName }}.csproj

      - name: Build
        run: dotnet build --configuration Release --no-restore src/${{ inputs.projectName }}/${{ inputs.projectName }}.csproj

      - name: Tests
        run: dotnet test -e ApiSettings__BaseUrl=${{ inputs.baseUrl }} -e ApiSettings__UserName="${{ secrets.userName }}" -e ApiSettings__Password="${{ secrets.password }}" --no-restore --verbosity normal --logger "trx;LogFileName=test-results.trx" src/${{ inputs.projectName }}/${{ inputs.projectName }}.csproj

      - uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results-${{ inputs.projectName }}
          path: '**/test-results.trx'    

        
        

    